### ISSUE TITLE
collapse does not work as intended

### ISSUE THREAD

**Issue by djpaterson** [aca13jmf/latex-document-outline#2]
On the outline the sections are accompanied by an arrow, indicating they can be collapsed. However, clicking the arrow does not collapse the section.

Reproduction steps:

1. Identify collapsible section of document
2. Click arrow

Expected result:
> section will collapse

Actual result
> section remains expanded

Reproduction rate:
10/10

Screenshot:
![image](https://user-images.githubusercontent.com/10195695/44265892-63187300-a220-11e8-96ed-afc10bdc2302.png)

**Comment by jmafoster1** [comment]
It was a problem with how I was binding the event handler. Easy fix :)
