### ISSUE TITLE
Document part with * should be left in the outline tree

### ISSUE THREAD

**Issue by EnochMakenp** [aca13jmf/latex-document-outline#3]
In LaTeX we may use * to signify that the document part (section, subsection, chapter...) should not be numbered - however these part are part of the document outline and I think it should appear in the outline tree, which, AFAICT, is not the case currently.
Thanks !

**Comment by jmafoster1** [comment]
That is a valid point which I didn't think about. I'll take a look when 
I get the chance, or feel free to submit a pull request...

**Comment by jmafoster1** [comment]
I've updated the regex so that these match now, and published an update.

**Comment by EnochMakenp** [comment]
Thanks a lot ! I checked it and it works as expected !

**Comment by EnochMakenp** [comment]
Sorry, I was too fast, after closer inspection I saw that the list of the content of a part placed before a starred part, is wrongly reported because it includes the content of the following starred part.
You see an example below - the Problems section is starred (not numbered), and you see that its content is duplicated in the subsection before (Thermal actuator). the same thing happen between 2 starred section, as can be seen with the Solutions section, whose content is duplicated at the end of the Problems section.
![image](https://user-images.githubusercontent.com/53652564/82380799-5c3c1700-9a29-11ea-9567-dcdb444f0705.png)

I suppose that it has something to do with the test deciding that the part is finished, and that this test should include the normal and the starred version of the part name... but I'm not so good at hacking and I've a hard time to figure what to look for in your code, sorry.

After reading more, I'm guessing that the culprit is the regEx in the getFigures function of the coffee.manager file, that is missing the possibility of a *... but that is all I can do, hope it helps.

**Comment by jmafoster1** [comment]
That is somewhat annoying. I'm also having a hard time figuring out my code, as I wrote it a while ago. I'll take a look at the weekend and see if I can fix it

**Comment by jmafoster1** [comment]
I'm just having a look at this now and I'm afraid I can't reproduce the problem. Would you be able to send me a minimum working example that reproduces the bug that I can use to test the code?

**Comment by EnochMakenp** [comment]
BTW, this issue is definitely not present anymore - a weirdness in my version at that time, it can be safely closed I think.

**Comment by EnochMakenp** [comment]
Again, I was too fast to call victory, sorry, the bug is still there :-(
But the good news is that I finally made a minimum case file... and then easily figured out the issue: in the manager.coffee file when you changed the rules for taking into account the * sections in the getStructure function, you did not change it in the getFigure and the getFigure collected figures until the next unstarred section, ignoring the starred one :-)

Probably no need to make a pull request for that: it is just a one liner in manager.coffee - line 98 should be the same as line 122 (it is missing the \*? bit after the sections names list). Maybe make it a class variable and have only one occurrence ?

I reopen the bug, but this time sure you can close it when the fix is in !

PS: for memory I've uploaded my minimum case file
[test-bug3.tex.txt](https://github.com/jmafoster1/latex-document-outline/files/12326531/test-bug3.tex.txt)
