### ISSUE TITLE
Strict variable declaration seems needed in Pulsar 1.107.1

### ISSUE THREAD

**Issue by EnochMakenp** [aca13jmf/latex-document-outline#7]
I'm the only one to bug you with bug reports, but thanks for your effort !

I've recently installed Pulsar (1.107.1 x64) and found that the latex-document-outline was no more working, with plenty of "str not defined" errors.

I had to use the let and const keywords each time a new variable was introduced in the latex-document-outline-view.js code... and it fixed the problem :-)

I suppose, there is now some strict ECMA script rule somewhere...

**Comment by jmafoster1** [comment]
I have also recently discovered Pulsar, but did not install this package as I only really wrote it for my thesis.
I am fairly busy with work now, so don't really have the time or energy to maintain this anymore. If you have fixed the problem, please feel free to submit a pull request, and I will merge it in. Or I could just give you write access to the repo if you would prefer?

**Comment by EnochMakenp** [comment]
I've created the pull request - be indulgent, it is my first one :-)
Thanks !

Note that I could see two improvements that I may want to do in the future:
- avoid the padding of non existing structure level (part and chapter for example outside book - which I guess you had in your PhD thesis :-) that offset the next levels (by 15px) and take unnecessary horizontal space
- collapse of structures level that contain only figure and table should be possible
Thus I may bug you by new pull requests if I do it in the future... but it may take time, and I need to need them badly :-)

**Comment by jmafoster1** [comment]
Thanks for this. I've merged the pull request and will look into releasing an updated version when I get chance, hopefully in the next couple of days. I agree with both of these changes.

**Comment by jmafoster1** [comment]
@EnochMakenp just fyi, I've published a new version, 1.3.16 to the Pulsar package manager

**Comment by EnochMakenp** [comment]
@jmafoster1 Finally, I got bored today and tried to make the promised update to the code, hence the new commit - it is a hack, as I did not understand (yet :-) all what you wrote, and simpler version may be possible, but it works nicely on my computer (Win10).
I suppose it is not urgent (as I said it works home :-), and we may wait for confirmation it works on another platform before pushing it, but it will probably require a version bump as behavior has been slightly changed.
Thanks for giving me this opportunity to help !
